[package]
name = "jxl-bitstream"
version = "0.1.0"
authors = ["Wonwoo Choi <chwo9843@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]

[dependencies.tracing]
version = "0.1.37"
default_features = false
features = ["std"]
