[package]
name = "jxl-frame"
version = "0.1.0"
authors = ["Wonwoo Choi <chwo9843@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]

[dependencies.crossbeam-channel]
version = "0.5.6"
optional = true

[dependencies.jxl-bitstream]
path = "../jxl-bitstream"

[dependencies.jxl-coding]
path = "../jxl-coding"

[dependencies.jxl-grid]
path = "../jxl-grid"

[dependencies.jxl-modular]
path = "../jxl-modular"

[dependencies.jxl-vardct]
path = "../jxl-vardct"

[dependencies.rayon]
version = "1.6.1"
optional = true

[dependencies.tracing]
version = "0.1.37"
default_features = false
features = ["std"]

[features]
mt = ["crossbeam-channel", "rayon"]
default = ["mt"]
