[package]
name = "jxl-oxide"
description = "JPEG XL decoder written in pure Rust"
authors = ["Wonwoo Choi <chwo9843@gmail.com>"]
repository = "https://github.com/tirr-c/jxl-oxide.git"
readme = "README.md"
keywords = ["jpeg-xl", "decoder", "jxl-oxide"]
categories = ["multimedia::images"]
license = "MIT OR Apache-2.0"

version = "0.1.0"
edition = "2021"

[dependencies]

[dependencies.jxl-bitstream]
version = "0.2.1"
path = "../jxl-bitstream"

[dependencies.jxl-color]
version = "0.3.0"
path = "../jxl-color"

[dependencies.jxl-frame]
version = "0.2.0"
path = "../jxl-frame"

[dependencies.jxl-grid]
version = "0.1.1"
path = "../jxl-grid"

[dependencies.jxl-image]
version = "0.3.0"
path = "../jxl-image"

[dependencies.jxl-render]
version = "0.1.0"
path = "../jxl-render"

[dependencies.tracing]
version = "0.1.37"
default_features = false
features = ["std"]

[dev-dependencies]
lcms2 = "5.5.0"

[dev-dependencies.reqwest]
version = "0.11.14"
features = ["blocking"]
